/** variant プリセット。キーは meta.json の variants[].id と対応する。 */
export const PRESETS = {
  parallax: {
    label: 'Depth Parallax',
    params: {
      mode: 'scene',
      parallaxSamples: 12,
      blurSamples: 10,
      zMultiplier: 0.72,
      shiftAmount: 0.2,
      shiftEase: 0.06,
      focus: 0.9,
      blurStrength: 0.008,
      aperture: 0.7,
      lightStrength: 0,
      lightRadius: 0.28,
      lightDepth: 0.85,
      lightColor: '#ffd9a8',
      corner: 0.06,
      vignette: 0.28,
      fogColor: '#16243d',
      fogAmount: 0.22,
      autoDemo: true,
      demoSpeed: 0.5,
    },
  },
  dof: {
    label: 'Rack Focus',
    params: {
      mode: 'scene',
      parallaxSamples: 12,
      blurSamples: 10,
      zMultiplier: 0.3,
      shiftAmount: 0.08,
      shiftEase: 0.05,
      focus: 0.9,
      blurStrength: 0.1,
      aperture: 1.1,
      lightStrength: 0,
      lightRadius: 0.28,
      lightDepth: 0.85,
      lightColor: '#ffd9a8',
      corner: 0.05,
      vignette: 0.45,
      fogColor: '#16243d',
      fogAmount: 0.4,
      autoDemo: true,
      demoSpeed: 0.35,
    },
  },
  flashlight: {
    label: 'Depth Flashlight',
    params: {
      mode: 'scene',
      parallaxSamples: 12,
      blurSamples: 6,
      zMultiplier: 0.38,
      shiftAmount: 0.1,
      shiftEase: 0.07,
      focus: 0.9,
      blurStrength: 0.022,
      aperture: 1,
      lightStrength: 1.5,
      lightRadius: 0.22,
      lightDepth: 0.88,
      lightColor: '#ffcf8f',
      corner: 0.06,
      vignette: 0.62,
      fogColor: '#0a1220',
      fogAmount: 0.6,
      autoDemo: true,
      demoSpeed: 0.55,
    },
  },
  depth: {
    label: 'Depth Map',
    params: {
      mode: 'depth',
      parallaxSamples: 12,
      blurSamples: 6,
      zMultiplier: 0.36,
      shiftAmount: 0.11,
      shiftEase: 0.06,
      focus: 0.55,
      blurStrength: 0.05,
      aperture: 1,
      lightStrength: 0,
      lightRadius: 0.28,
      lightDepth: 0.85,
      lightColor: '#ffd9a8',
      corner: 0.06,
      vignette: 0,
      fogColor: '#16243d',
      fogAmount: 0,
      autoDemo: true,
      demoSpeed: 0.5,
    },
  },
}

export const MODES = ['scene', 'depth']

export const DEFAULT_PRESET = 'parallax'
export const DEFAULTS = PRESETS[DEFAULT_PRESET].params

/** leva の options 用 { ラベル: id } テーブル */
export const PRESET_OPTIONS = Object.fromEntries(
  Object.entries(PRESETS).map(([id, p]) => [p.label, id]),
)
