/** variant プリセット。キーは meta.json の variants[].id と対応する。 */
export const PRESETS = {
  gold: {
    label: 'Gold Pulse',
    params: {
      geometry: 'sphere',
      pattern: 'noise',
      patternScale: 42,
      lifetime: 2.2,
      maxRadius: 2.3,
      ringWidth: 0.3,
      sharpness: 2.2,
      ease: 2.4,
      frequency: 16,
      tailFalloff: 0.75,
      pixellation: 190,
      uvMixMultiplier: 6,
      mosaicFocus: 1.6,
      pulseColor: '#ff8000',
      pulseIntensity: 7,
      pulseGamma: 1.15,
      hueShift: 1,
      baseColor: '#1a1a1a',
      accentColor: '#b4b4b4',
      idleInterval: 1.1,
      autoRipple: true,
    },
  },
  ice: {
    label: 'Ice Mosaic',
    params: {
      geometry: 'sphere',
      pattern: 'grid',
      patternScale: 60,
      lifetime: 2.6,
      maxRadius: 2.35,
      ringWidth: 0.34,
      sharpness: 1.6,
      ease: 2.2,
      frequency: 11,
      tailFalloff: 0.6,
      pixellation: 120,
      uvMixMultiplier: 7,
      mosaicFocus: 1.2,
      pulseColor: '#3fd0ff',
      pulseIntensity: 6.5,
      pulseGamma: 1.1,
      hueShift: 0,
      baseColor: '#0b141c',
      accentColor: '#4d86ab',
      idleInterval: 1.5,
      autoRipple: true,
    },
  },
  scanline: {
    label: 'Dense Scanline',
    params: {
      geometry: 'plane',
      pattern: 'stripes',
      patternScale: 48,
      lifetime: 1.8,
      maxRadius: 3.9,
      ringWidth: 0.26,
      sharpness: 3,
      ease: 2.8,
      frequency: 30,
      tailFalloff: 1.1,
      pixellation: 260,
      uvMixMultiplier: 5,
      mosaicFocus: 2.2,
      pulseColor: '#b6ff5c',
      pulseIntensity: 4,
      pulseGamma: 1.15,
      hueShift: 0,
      baseColor: '#101010',
      accentColor: '#5c6b55',
      idleInterval: 0.8,
      autoRipple: true,
    },
  },
  magma: {
    label: 'Magma Bloom',
    params: {
      geometry: 'torus',
      pattern: 'voronoi',
      patternScale: 34,
      lifetime: 2.8,
      maxRadius: 2.6,
      ringWidth: 0.4,
      sharpness: 1.3,
      ease: 2.0,
      frequency: 8,
      tailFalloff: 0.5,
      pixellation: 90,
      uvMixMultiplier: 8,
      mosaicFocus: 1.1,
      pulseColor: '#ff2d00',
      pulseIntensity: 7.5,
      pulseGamma: 1.15,
      hueShift: 1,
      baseColor: '#170805',
      accentColor: '#9c4520',
      idleInterval: 1.8,
      autoRipple: true,
    },
  },
}

export const PATTERNS = ['noise', 'grid', 'voronoi', 'stripes']

export const DEFAULT_PRESET = 'gold'
export const DEFAULTS = PRESETS[DEFAULT_PRESET].params

/** leva の options 用 { ラベル: id } テーブル */
export const PRESET_OPTIONS = Object.fromEntries(
  Object.entries(PRESETS).map(([id, p]) => [p.label, id]),
)
