/** variant プリセット。キーは meta.json の variants[].id と対応する。 */
export const PRESETS = {
  full: {
    label: 'Full Stack',
    params: {
      threshold: 1.0,
      knee: 0.6,
      strength: 0.7,
      spread: 1.3,
      falloff: 0.6,
      ghostSpacing: 0.32,
      ghostStrength: 0.22,
      haloRadius: 0.12,
      haloStrength: 0.15,
      chroma: 0.25,
      lut: 'tealOrange',
      lutMix: 0.85,
      exposure: 1.0,
      vignette: 0.55,
      grain: 0.035,
      lampColor: '#ffd2a0',
      lampIntensity: 6.5,
      signColor: '#ff4f8b',
      signIntensity: 5.0,
      compare: 0.42,
    },
  },
  bloomOnly: {
    label: 'Bloom Only',
    params: {
      threshold: 0.95,
      knee: 0.5,
      strength: 0.9,
      spread: 1.6,
      falloff: 0.75,
      ghostSpacing: 0.32,
      ghostStrength: 0,
      haloRadius: 0.38,
      haloStrength: 0,
      chroma: 0,
      lut: 'neutral',
      lutMix: 0,
      exposure: 1.0,
      vignette: 0,
      grain: 0,
      lampColor: '#ffffff',
      lampIntensity: 6.0,
      signColor: '#7fd4ff',
      signIntensity: 4.5,
      compare: 0.42,
    },
  },
  gradeOnly: {
    label: 'Grade Only',
    params: {
      threshold: 3.0,
      knee: 0.5,
      strength: 0,
      spread: 1.0,
      falloff: 0.9,
      ghostSpacing: 0.32,
      ghostStrength: 0,
      haloRadius: 0.38,
      haloStrength: 0,
      chroma: 0,
      lut: 'bleach',
      lutMix: 1.0,
      exposure: 1.0,
      vignette: 0.35,
      grain: 0.05,
      lampColor: '#ffe6c2',
      lampIntensity: 3.0,
      signColor: '#9fb4c8',
      signIntensity: 2.4,
      compare: 0.42,
    },
  },
  anamorphic: {
    label: 'Anamorphic',
    params: {
      threshold: 0.9,
      knee: 0.75,
      strength: 0.85,
      spread: 1.9,
      falloff: 0.8,
      ghostSpacing: 0.46,
      ghostStrength: 0.6,
      haloRadius: 0.14,
      haloStrength: 0.18,
      chroma: 0.7,
      lut: 'night',
      lutMix: 0.9,
      exposure: 1.25,
      vignette: 0.7,
      grain: 0.05,
      lampColor: '#cfe2ff',
      lampIntensity: 7.5,
      signColor: '#ff7a5c',
      signIntensity: 5.5,
      compare: 0.0,
    },
  },
}

export const DEFAULT_PRESET = 'full'
export const DEFAULTS = PRESETS[DEFAULT_PRESET].params

/** leva の options 用 { ラベル: id } テーブル */
export const PRESET_OPTIONS = Object.fromEntries(
  Object.entries(PRESETS).map(([id, p]) => [p.label, id]),
)
