/** variant プリセット。キーは meta.json の variants[].id と対応する。 */
const BASE = {
  segLength: 0.1,
  smoothing: 6,
  maxLength: 4.5,
  growSpeed: 4,
  radius: 0.035,
  taper: 0.55,
  petals: 6,
  flowerScale: 1.6,
  bloomAt: 2.6,
  bloomTime: 2.2,
  maxPlants: 10,
  colorBase: '#1f5a34',
  colorTip: '#7fd88a',
  hueBase: 0.92,
  hueSpread: 0.3,
  coreColor: '#ffd66b',
  groundY: -1.6,
  groundColor: '#33513e',
  background: '#0a1014',
  autoDemo: true,
  idleDelay: 1.2,
  demoSpeed: 1.1,
  demoLength: 3.4,
}

export const PRESETS = {
  flower: { label: 'Flower', params: { ...BASE } },
  vine: {
    label: 'Vine',
    params: {
      ...BASE,
      segLength: 0.07,
      smoothing: 4,
      maxLength: 7,
      growSpeed: 3,
      radius: 0.022,
      taper: 0.75,
      petals: 4,
      flowerScale: 0.95,
      bloomAt: 4.5,
      bloomTime: 3,
      colorBase: '#28402a',
      colorTip: '#9ad46b',
      hueBase: 0.28,
      hueSpread: 0.12,
      coreColor: '#e8f0a0',
      groundColor: '#2b4432',
      background: '#080d0b',
      demoLength: 5.2,
    },
  },
  neon: {
    label: 'Neon',
    params: {
      ...BASE,
      segLength: 0.12,
      smoothing: 9,
      maxLength: 4,
      growSpeed: 6,
      radius: 0.05,
      taper: 0.2,
      petals: 8,
      flowerScale: 1.9,
      bloomAt: 2,
      bloomTime: 1.4,
      colorBase: '#2a1550',
      colorTip: '#7cf0ff',
      hueBase: 0.55,
      hueSpread: 0.4,
      coreColor: '#ffffff',
      groundColor: '#2a2350',
      background: '#070512',
      demoSpeed: 1.5,
    },
  },
  thicket: {
    label: 'Thicket',
    params: {
      ...BASE,
      segLength: 0.09,
      smoothing: 7,
      maxLength: 3.4,
      growSpeed: 7,
      radius: 0.028,
      taper: 0.6,
      petals: 5,
      flowerScale: 1.3,
      bloomAt: 1.8,
      bloomTime: 1.6,
      maxPlants: 20,
      hueBase: 0.05,
      hueSpread: 0.5,
      groundColor: '#4a382a',
      background: '#100c0a',
      idleDelay: 0.4,
      demoSpeed: 1.8,
      demoLength: 2.6,
    },
  },
}

export const DEFAULT_PRESET = 'flower'
export const DEFAULTS = PRESETS[DEFAULT_PRESET].params

/** leva の options 用 { ラベル: id } テーブル */
export const PRESET_OPTIONS = Object.fromEntries(
  Object.entries(PRESETS).map(([id, p]) => [p.label, id]),
)
