/** variant プリセット。キーは meta.json の variants[].id と対応する。 */
export const PRESETS = {
  orb: {
    label: 'Curl Orb',
    params: {
      shape: 'sphere',
      resolution: 256,
      rotationSpeed: 0.05,
      curlSize: 2.4,
      curlSpeed: 0.14,
      curlStrength: 0.055,
      octaves: 2,
      shapeStrength: 1,
      lerpSpeed: 0.06,
      swirl: 0,
      mouseStrength: 0.9,
      mouseRadius: 0.85,
      size: 0.011,
      speedStretch: 22,
      intensity: 0.95,
      speedTint: 7,
      falloff: 2.2,
      colorA: '#3d6bff',
      colorB: '#00e0ff',
      colorHot: '#fff2c4',
    },
  },
  nebula: {
    label: 'Free Nebula',
    params: {
      shape: 'sphere',
      resolution: 256,
      rotationSpeed: 0.02,
      curlSize: 0.55,
      curlSpeed: 0.09,
      curlStrength: 0.55,
      octaves: 3,
      shapeStrength: 0.06,
      lerpSpeed: 0.09,
      swirl: 0,
      mouseStrength: 1.4,
      mouseRadius: 1.1,
      size: 0.0105,
      speedStretch: 30,
      intensity: 0.85,
      speedTint: 5,
      falloff: 2.6,
      colorA: '#8b2bff',
      colorB: '#ff3d9a',
      colorHot: '#ffe7b0',
    },
  },
  galaxy: {
    label: 'Galaxy Disc',
    params: {
      shape: 'disc',
      resolution: 256,
      rotationSpeed: 0.04,
      curlSize: 1.4,
      curlSpeed: 0.07,
      curlStrength: 0.06,
      octaves: 1,
      shapeStrength: 0.55,
      lerpSpeed: 0.05,
      swirl: 0.35,
      mouseStrength: 0.7,
      mouseRadius: 0.7,
      size: 0.0095,
      speedStretch: 40,
      intensity: 0.95,
      speedTint: 9,
      falloff: 2.0,
      colorA: '#ffb04d',
      colorB: '#ff5c7a',
      colorHot: '#ffffff',
    },
  },
  helix: {
    label: 'Helix Lock',
    params: {
      shape: 'helix',
      resolution: 256,
      rotationSpeed: 0.14,
      curlSize: 2.2,
      curlSpeed: 0.2,
      curlStrength: 0.05,
      octaves: 1,
      shapeStrength: 1,
      lerpSpeed: 0.1,
      swirl: 0,
      mouseStrength: 1.6,
      mouseRadius: 0.6,
      size: 0.012,
      speedStretch: 18,
      intensity: 1.05,
      speedTint: 8,
      falloff: 2.4,
      colorA: '#25f4a0',
      colorB: '#2bb8ff',
      colorHot: '#eaffd0',
    },
  },
}

export const RESOLUTIONS = { '64² (4k)': 64, '128² (16k)': 128, '256² (65k)': 256, '384² (147k)': 384 }

export const DEFAULT_PRESET = 'orb'
export const DEFAULTS = PRESETS[DEFAULT_PRESET].params

/** leva の options 用 { ラベル: id } テーブル */
export const PRESET_OPTIONS = Object.fromEntries(
  Object.entries(PRESETS).map(([id, p]) => [p.label, id]),
)
