/** variant プリセット。キーは meta.json の variants[].id と対応する。 */
export const PRESETS = {
  hex: {
    label: 'Hex Shatter',
    params: {
      mode: 'hex',
      direction: 0,
      edge: 0.12,
      noiseScale: 3,
      noiseAmount: 0.18,
      flash: 0,
      zoom: 0,
      overlayColor: '#0a0d14',
      slope: 0.2,
      parallax: 0.4,
      displace: 0.025,
      ca: 12,
      hexScale: 9,
      hexJitter: 0.22,
      hexWarp: 0.12,
      hexEdge: 0.06,
      hexRefract: 0.03,
      hexSpin: 1.2,
      hexWindow: 0.28,
      hexReach: 0.18,
      edgeColor: '#8fe6ff',
      duration: 1.8,
    },
  },

  ice: {
    label: 'Ice Cut',
    params: {
      mode: 'ice-cut',
      direction: 0,
      edge: 0.12,
      noiseScale: 3,
      noiseAmount: 0.18,
      flash: 0,
      zoom: 0,
      overlayColor: '#0a0d14',
      slope: 0.2,
      parallax: 0.4,
      displace: 0.025,
      ca: 12,
      hexScale: 9,
      hexJitter: 0.22,
      hexWarp: 0.12,
      hexEdge: 0.06,
      hexRefract: 0.03,
      hexSpin: 1.2,
      hexWindow: 0.28,
      hexReach: 0.18,
      edgeColor: '#8fe6ff',
      duration: 1.6,
    },
  },

  'noise-wipe': {
    label: 'Noise Wipe',
    params: {
      mode: 'noise-wipe',
      duration: 1.6,
      direction: 0,
      edge: 0.12,
      noiseScale: 3.2,
      noiseAmount: 0.2,
      flash: 0.4,
      zoom: 0.04,
      overlayColor: '#f25a5a',
      slope: 0.2,
      parallax: 0.4,
      displace: 0.025,
      ca: 12,
      hexScale: 9,
      hexJitter: 0.22,
      hexWarp: 0.12,
      hexEdge: 0.06,
      hexRefract: 0.03,
      hexSpin: 1.2,
      hexWindow: 0.28,
      hexReach: 0.18,
      edgeColor: '#8fe6ff',
    },
  },
  curtain: {
    label: 'Theater Curtain',
    params: {
      mode: 'curtain',
      duration: 2.4,
      direction: 0,
      edge: 0.02,
      noiseScale: 3.2,
      noiseAmount: 0,
      flash: 0,
      zoom: 0,
      overlayColor: '#f25a5a',
      slope: 0.2,
      parallax: 0.4,
      displace: 0.025,
      ca: 12,
      hexScale: 9,
      hexJitter: 0.22,
      hexWarp: 0.12,
      hexEdge: 0.06,
      hexRefract: 0.03,
      hexSpin: 1.2,
      hexWindow: 0.28,
      hexReach: 0.18,
      edgeColor: '#8fe6ff',
    },
  },
  fade: {
    label: 'Overlay Fade',
    params: {
      mode: 'fade',
      duration: 1.8,
      direction: 0,
      edge: 0.1,
      noiseScale: 3.2,
      noiseAmount: 0,
      flash: 0,
      zoom: 0,
      overlayColor: '#151d47',
      slope: 0.2,
      parallax: 0.4,
      displace: 0.025,
      ca: 12,
      hexScale: 9,
      hexJitter: 0.22,
      hexWarp: 0.12,
      hexEdge: 0.06,
      hexRefract: 0.03,
      hexSpin: 1.2,
      hexWindow: 0.28,
      hexReach: 0.18,
      edgeColor: '#8fe6ff',
    },
  },
  circle: {
    label: 'Circle Wipe',
    params: {
      mode: 'circle',
      duration: 1.4,
      direction: 0,
      edge: 0.06,
      noiseScale: 6,
      noiseAmount: 0.08,
      flash: 0.5,
      zoom: 0.12,
      overlayColor: '#151d47',
      slope: 0.2,
      parallax: 0.4,
      displace: 0.025,
      ca: 12,
      hexScale: 9,
      hexJitter: 0.22,
      hexWarp: 0.12,
      hexEdge: 0.06,
      hexRefract: 0.03,
      hexSpin: 1.2,
      hexWindow: 0.28,
      hexReach: 0.18,
      edgeColor: '#8fe6ff',
    },
  },
}

export const MODES = ['noise-wipe', 'curtain', 'fade', 'circle', 'ice-cut', 'hex']

export const DEFAULT_PRESET = 'hex'
export const DEFAULTS = PRESETS[DEFAULT_PRESET].params

/** leva の options 用 { ラベル: id } テーブル */
export const PRESET_OPTIONS = Object.fromEntries(
  Object.entries(PRESETS).map(([id, p]) => [p.label, id]),
)
