/** variant プリセット。キーは meta.json の variants[].id と対応する。 */
export const PRESETS = {
  orbit: {
    label: 'Orbit',
    params: {
      count: 1400,
      radiusMin: 0.055,
      radiusMax: 0.11,
      gravity: 5.5,
      downward: 0,
      damping: 0.06,
      restitution: 0.35,
      container: 4.6,
      floor: false,
      spin: 0.5,
      pointerRadius: 1.5,
      pointerForce: 46,
      substeps: 2,
      showGrid: false,
      colorSlow: '#2f6df0',
      colorFast: '#ffd27a',
      speedScale: 2.6,
    },
  },
  pit: {
    label: 'Drop Pit',
    params: {
      count: 1200,
      radiusMin: 0.07,
      radiusMax: 0.13,
      gravity: 0,
      downward: 9.2,
      damping: 0.02,
      restitution: 0.12,
      container: 3.6,
      floor: true,
      spin: 0.1,
      pointerRadius: 1.4,
      pointerForce: 60,
      substeps: 3,
      showGrid: false,
      colorSlow: '#3c8f6b',
      colorFast: '#f2e8a0',
      speedScale: 3.4,
    },
  },
  cursor: {
    label: 'Cursor Push',
    params: {
      count: 1500,
      radiusMin: 0.06,
      radiusMax: 0.1,
      gravity: 2.2,
      downward: 0,
      damping: 0.5,
      restitution: 0.2,
      container: 4.2,
      floor: false,
      spin: 0.15,
      pointerRadius: 2.0,
      pointerForce: 120,
      substeps: 2,
      showGrid: false,
      colorSlow: '#7a3cf0',
      colorFast: '#ff9ad2',
      speedScale: 4.5,
    },
  },
  grid: {
    label: 'Broadphase',
    params: {
      count: 900,
      radiusMin: 0.09,
      radiusMax: 0.15,
      gravity: 4.5,
      downward: 0,
      damping: 0.08,
      restitution: 0.3,
      container: 4.2,
      floor: false,
      spin: 0.45,
      pointerRadius: 1.6,
      pointerForce: 50,
      substeps: 2,
      showGrid: true,
      colorSlow: '#2f6df0',
      colorFast: '#ffd27a',
      speedScale: 2.6,
    },
  },
}

export const DEFAULT_PRESET = 'orbit'
export const DEFAULTS = PRESETS[DEFAULT_PRESET].params

/** leva の options 用 { ラベル: id } テーブル */
export const PRESET_OPTIONS = Object.fromEntries(
  Object.entries(PRESETS).map(([id, p]) => [p.label, id]),
)
